# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0b3 on Fri Feb 16 14:01:02 2018
#

import wx
import wx.adv

from src.views.akDownloadView import AkDownloadView
from src.views.akImportView import AkImportView

class AkHistoricalView(wx.Dialog):
    def __init__(self, parent, controller):
        style = wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        super(AkHistoricalView, self).__init__(parent, style=style)
        self.SetInitialSize((766, 537))
        
        self.controller = controller
        self.controller.Register(self)
        
        self.notebook = wx.Notebook(self, wx.ID_ANY)
        
        self.importView = AkImportView(self.notebook, self.controller)
        self.downloadView = AkDownloadView(self.notebook, self.controller)

        self.__set_properties()
        self.__do_layout()
        
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Bind(wx.EVT_WINDOW_DESTROY, self.OnDestroy)


    def __set_properties(self):
        self.SetTitle("Historical Data Manager")

    def __do_layout(self):                
        sizer = wx.BoxSizer(wx.VERTICAL)

        self.notebook.AddPage(self.importView, "Import")
        self.notebook.AddPage(self.downloadView, "Download")              
        sizer.Add(self.notebook, 1, wx.EXPAND, 0)
        
        self.SetSizer(sizer)
        self.Layout()
        
    def OnClose(self, event):
        print('In OnClose')
        event.Skip()

    def OnDestroy(self, event):
        print('In OnDestroy')
        event.Skip()