# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0b3 on Sun Mar 11 20:18:05 2018
#

import wx
import wx.adv

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class AkHistoricalDataManager(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AkHistoricalDataManager.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((766, 537))
        self.histDataMngr = wx.Notebook(self, wx.ID_ANY)
        self.panel_1 = wx.Panel(self.histDataMngr, wx.ID_ANY)
        self.cbInputFormat = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Trade Workstation", "Metatrader 4"], style=wx.CB_DROPDOWN)
        self.cbTimeZone = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["UTC"], style=wx.CB_DROPDOWN)
        self.btnStartImport = wx.Button(self.panel_1, wx.ID_ANY, "Start Import")
        self.histDataMngr_Download = wx.Panel(self.histDataMngr, wx.ID_ANY)
        self.instrumentsTree = wx.TreeCtrl(self.histDataMngr_Download, wx.ID_ANY)
        self.btnDownload = wx.Button(self.histDataMngr_Download, wx.ID_ANY, "Download")
        self.lstData = wx.ListCtrl(self.histDataMngr_Download, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.enableStartDatePicker = wx.CheckBox(self.histDataMngr_Download, wx.ID_ANY, "")
        self.startDatePicker = wx.adv.DatePickerCtrl(self.histDataMngr_Download, wx.ID_ANY)
        self.enableEndDatePicker = wx.CheckBox(self.histDataMngr_Download, wx.ID_ANY, "")
        self.endDatePicker = wx.adv.DatePickerCtrl(self.histDataMngr_Download, wx.ID_ANY)
        self.btnFilter = wx.Button(self.histDataMngr_Download, wx.ID_ANY, "Filter")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AkHistoricalDataManager.__set_properties
        self.SetTitle("Historical Data Manager")
        self.cbInputFormat.SetSelection(0)
        self.cbTimeZone.SetSelection(0)
        self.btnDownload.SetMinSize((182, 26))
        self.lstData.AppendColumn("N", format=wx.LIST_FORMAT_LEFT, width=41)
        self.lstData.AppendColumn("Date", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lstData.AppendColumn("Open", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lstData.AppendColumn("High", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lstData.AppendColumn("Low", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lstData.AppendColumn("Close", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.startDatePicker.SetMinSize((123, 23))
        self.endDatePicker.SetMinSize((123, 23))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AkHistoricalDataManager.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        DataListBox = wx.BoxSizer(wx.VERTICAL)
        editDataListBox = wx.StaticBoxSizer(wx.StaticBox(self.histDataMngr_Download, wx.ID_ANY, "Filter data"), wx.HORIZONTAL)
        FilterDataBox = wx.BoxSizer(wx.VERTICAL)
        FilterDateSizer = wx.FlexGridSizer(0, 3, 0, 0)
        SymbolsBox = wx.BoxSizer(wx.VERTICAL)
        ImportSizer = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, ""), wx.HORIZONTAL)
        ImportComboBox = wx.BoxSizer(wx.VERTICAL)
        ImportLablesBox = wx.BoxSizer(wx.VERTICAL)
        lblInpurFormat = wx.StaticText(self.panel_1, wx.ID_ANY, "Data Input Format")
        ImportLablesBox.Add(lblInpurFormat, 0, wx.ALL, 20)
        lblTimeZone = wx.StaticText(self.panel_1, wx.ID_ANY, "Time zone of imported data:")
        ImportLablesBox.Add(lblTimeZone, 0, wx.ALL, 20)
        ImportSizer.Add(ImportLablesBox, 1, wx.EXPAND, 0)
        ImportComboBox.Add(self.cbInputFormat, 0, wx.ALL | wx.EXPAND, 15)
        ImportComboBox.Add(self.cbTimeZone, 0, wx.ALL | wx.EXPAND, 15)
        ImportComboBox.Add(self.btnStartImport, 0, wx.ALL, 15)
        ImportSizer.Add(ImportComboBox, 2, wx.EXPAND, 0)
        self.panel_1.SetSizer(ImportSizer)
        lblSymbols = wx.StaticText(self.histDataMngr_Download, wx.ID_ANY, "Symbols:")
        SymbolsBox.Add(lblSymbols, 0, wx.BOTTOM | wx.TOP, 5)
        SymbolsBox.Add(self.instrumentsTree, 1, wx.EXPAND, 0)
        SymbolsBox.Add(self.btnDownload, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 15)
        sizer_2.Add(SymbolsBox, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
        lblDatabase = wx.StaticText(self.histDataMngr_Download, wx.ID_ANY, "Database:")
        DataListBox.Add(lblDatabase, 0, wx.BOTTOM | wx.TOP, 5)
        DataListBox.Add(self.lstData, 1, wx.EXPAND, 0)
        lblStartDate = wx.StaticText(self.histDataMngr_Download, wx.ID_ANY, "Start date:")
        FilterDateSizer.Add(lblStartDate, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        FilterDateSizer.Add(self.enableStartDatePicker, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        FilterDateSizer.Add(self.startDatePicker, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        lblEndDate = wx.StaticText(self.histDataMngr_Download, wx.ID_ANY, "End date:")
        FilterDateSizer.Add(lblEndDate, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        FilterDateSizer.Add(self.enableEndDatePicker, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        FilterDateSizer.Add(self.endDatePicker, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        FilterDataBox.Add(FilterDateSizer, 1, wx.ALIGN_CENTER | wx.EXPAND, 0)
        FilterDataBox.Add(self.btnFilter, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        editDataListBox.Add(FilterDataBox, 0, wx.EXPAND, 0)
        editDataListBox.Add((60, 0), 1, 0, 0)
        DataListBox.Add(editDataListBox, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.BOTTOM | wx.EXPAND | wx.TOP, 0)
        sizer_2.Add(DataListBox, 2, wx.EXPAND, 0)
        self.histDataMngr_Download.SetSizer(sizer_2)
        self.histDataMngr.AddPage(self.panel_1, "Import")
        self.histDataMngr.AddPage(self.histDataMngr_Download, "Download")
        sizer_1.Add(self.histDataMngr, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class AkHistoricalDataManager
