# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0b3 on Tue Feb 27 22:55:17 2018
#

import wx
import wx.adv

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class AkNotebookMain(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AkNotebookMain.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((867, 560))
        self.btn_Calculate = wx.Button(self, wx.ID_ANY, "Calculate")
        self.notebook_Main = wx.Notebook(self, wx.ID_ANY)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_Main, wx.ID_ANY)
        self.notebook_Main_Graphs = wx.Panel(self.notebook_Main, wx.ID_ANY)
        self.notebook_Main_Periods = wx.Panel(self.notebook_Main, wx.ID_ANY)
        self.notebook_Main_Journal = wx.Panel(self.notebook_Main, wx.ID_ANY)
        self.calendar_Note = wx.adv.CalendarCtrl(self.notebook_Main_Journal, wx.ID_ANY)
        self.btn_Ok = wx.Button(self.notebook_Main_Journal, wx.ID_ANY, "OK")
        self.btn_Clear = wx.Button(self.notebook_Main_Journal, wx.ID_ANY, "Clear")
        self.text_Note = wx.TextCtrl(self.notebook_Main_Journal, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_RICH2)
        self.lst_JournalNotes = wx.ListCtrl(self.notebook_Main_Journal, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onAddNoteJournalHandler, self.btn_Ok)
        self.Bind(wx.EVT_BUTTON, self.onClearJournalHandler, self.btn_Clear)
        self.Bind(wx.EVT_LIST_ITEM_RIGHT_CLICK, self.onNotesItemRightClickHandler, self.lst_JournalNotes)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AkNotebookMain.__set_properties
        self.SetTitle("Notebook Main")
        self.btn_Ok.SetMinSize((60, 26))
        self.btn_Clear.SetMinSize((60, 26))
        self.text_Note.SetMinSize((740, 190))
        self.lst_JournalNotes.AppendColumn("Date", format=wx.LIST_FORMAT_LEFT, width=372)
        self.lst_JournalNotes.AppendColumn("Note", format=wx.LIST_FORMAT_LEFT, width=304)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AkNotebookMain.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer_Journal = wx.BoxSizer(wx.VERTICAL)
        hBox_TopJournal = wx.BoxSizer(wx.HORIZONTAL)
        hBox_TextNote = wx.BoxSizer(wx.HORIZONTAL)
        vBox_Calendar = wx.BoxSizer(wx.VERTICAL)
        hBox_Buttons = wx.BoxSizer(wx.HORIZONTAL)
        hBox_Calculate = wx.BoxSizer(wx.HORIZONTAL)
        hBox_Calculate.Add(self.btn_Calculate, 0, 0, 0)
        hBox_Calculate.Add((0, 0), 0, 0, 0)
        hBox_Calculate.Add((0, 0), 0, 0, 0)
        hBox_Calculate.Add((0, 0), 0, 0, 0)
        hBox_Calculate.Add((0, 0), 0, 0, 0)
        hBox_Calculate.Add((0, 0), 0, 0, 0)
        hBox_Calculate.Add((0, 0), 0, 0, 0)
        sizer.Add(hBox_Calculate, 0, wx.ALL | wx.EXPAND, 10)
        vBox_Calendar.Add(self.calendar_Note, 0, 0, 0)
        hBox_Buttons.Add(self.btn_Ok, 0, wx.LEFT | wx.RIGHT, 5)
        hBox_Buttons.Add(self.btn_Clear, 0, 0, 0)
        vBox_Calendar.Add(hBox_Buttons, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        hBox_TopJournal.Add(vBox_Calendar, 0, 0, 0)
        hBox_TextNote.Add(self.text_Note, 1, wx.EXPAND, 0)
        hBox_TopJournal.Add(hBox_TextNote, 1, wx.EXPAND, 0)
        sizer_Journal.Add(hBox_TopJournal, 1, wx.EXPAND, 0)
        sizer_Journal.Add(self.lst_JournalNotes, 2, wx.EXPAND, 0)
        self.notebook_Main_Journal.SetSizer(sizer_Journal)
        self.notebook_Main.AddPage(self.notebook_1_pane_1, "Summary")
        self.notebook_Main.AddPage(self.notebook_Main_Graphs, "Graphs")
        self.notebook_Main.AddPage(self.notebook_Main_Periods, "Periods")
        self.notebook_Main.AddPage(self.notebook_Main_Journal, "Journal")
        sizer.Add(self.notebook_Main, 1, wx.ALL | wx.EXPAND, 5)
        self.SetSizer(sizer)
        self.Layout()
        # end wxGlade

    def onAddNoteJournalHandler(self, event):  # wxGlade: AkNotebookMain.<event_handler>
        print("Event handler 'onAddNoteJournalHandler' not implemented!")
        event.Skip()

    def onClearJournalHandler(self, event):  # wxGlade: AkNotebookMain.<event_handler>
        print("Event handler 'onClearJournalHandler' not implemented!")
        event.Skip()

    def onNotesItemRightClickHandler(self, event):  # wxGlade: AkNotebookMain.<event_handler>
        print("Event handler 'onNotesItemRightClickHandler' not implemented!")
        event.Skip()

# end of class AkNotebookMain
